# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.candles_graph = GraphicsWindow()#self.tab)
        self.candles_graph.setObjectName("candles_graph")
        self.verticalLayout.addWidget(self.candles_graph)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.slider_end = QtWidgets.QScrollBar(self.tab)
        self.slider_end.setEnabled(False)
        self.slider_end.setOrientation(QtCore.Qt.Horizontal)
        self.slider_end.setObjectName("slider_end")
        self.gridLayout_2.addWidget(self.slider_end, 1, 2, 1, 1)
        self.slider_begin = QtWidgets.QScrollBar(self.tab)
        self.slider_begin.setEnabled(False)
        self.slider_begin.setOrientation(QtCore.Qt.Horizontal)
        self.slider_begin.setObjectName("slider_begin")
        self.gridLayout_2.addWidget(self.slider_begin, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(40, 70))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMaximumSize(QtCore.QSize(40, 70))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.range_begin_dt = QtWidgets.QDateTimeEdit(self.tab)
        self.range_begin_dt.setEnabled(False)
        self.range_begin_dt.setMaximumSize(QtCore.QSize(140, 200))
        self.range_begin_dt.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.range_begin_dt.setTimeSpec(QtCore.Qt.UTC)
        self.range_begin_dt.setObjectName("range_begin_dt")
        self.gridLayout_2.addWidget(self.range_begin_dt, 0, 1, 1, 1)
        self.range_end_dt = QtWidgets.QDateTimeEdit(self.tab)
        self.range_end_dt.setEnabled(False)
        self.range_end_dt.setMaximumSize(QtCore.QSize(140, 200))
        self.range_end_dt.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.range_end_dt.setTimeSpec(QtCore.Qt.UTC)
        self.range_end_dt.setObjectName("range_end_dt")
        self.gridLayout_2.addWidget(self.range_end_dt, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BTC_graph = GraphicsWindow()#self.tab)
        self.BTC_graph.setObjectName("BTC_graph")
        self.horizontalLayout_3.addWidget(self.BTC_graph)
        self.USD_graph = GraphicsWindow()#self.tab)
        self.USD_graph.setObjectName("USD_graph")
        self.horizontalLayout_3.addWidget(self.USD_graph)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pair_test = QtWidgets.QComboBox(self.tab)
        self.pair_test.setMaximumSize(QtCore.QSize(100, 150))
        self.pair_test.setObjectName("pair_test")
        self.gridLayout.addWidget(self.pair_test, 0, 1, 1, 1)
        self.last_buy_price_test = QtWidgets.QLineEdit(self.tab)
        self.last_buy_price_test.setMaximumSize(QtCore.QSize(100, 150))
        self.last_buy_price_test.setObjectName("last_buy_price_test")
        self.gridLayout.addWidget(self.last_buy_price_test, 6, 1, 1, 1)
        self.clear_main_plot_button = QtWidgets.QPushButton(self.tab)
        self.clear_main_plot_button.setEnabled(False)
        self.clear_main_plot_button.setMaximumSize(QtCore.QSize(130, 150))
        self.clear_main_plot_button.setObjectName("clear_main_plot_button")
        self.gridLayout.addWidget(self.clear_main_plot_button, 17, 0, 1, 1)
        self.show_real_button = QtWidgets.QPushButton(self.tab)
        self.show_real_button.setEnabled(False)
        self.show_real_button.setMaximumSize(QtCore.QSize(250, 250))
        self.show_real_button.setObjectName("show_real_button")
        self.gridLayout.addWidget(self.show_real_button, 15, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMaximumSize(QtCore.QSize(130, 150))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMaximumSize(QtCore.QSize(130, 150))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMaximumSize(QtCore.QSize(130, 150))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMaximumSize(QtCore.QSize(130, 150))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 14, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMaximumSize(QtCore.QSize(130, 150))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.ts_analysis_button = QtWidgets.QPushButton(self.tab)
        self.ts_analysis_button.setEnabled(False)
        self.ts_analysis_button.setMaximumSize(QtCore.QSize(250, 250))
        self.ts_analysis_button.setObjectName("ts_analysis_button")
        self.gridLayout.addWidget(self.ts_analysis_button, 11, 0, 1, 2)
        self.wallet_parts_test = QtWidgets.QSpinBox(self.tab)
        self.wallet_parts_test.setMaximumSize(QtCore.QSize(100, 150))
        self.wallet_parts_test.setProperty("value", 3)
        self.wallet_parts_test.setObjectName("wallet_parts_test")
        self.gridLayout.addWidget(self.wallet_parts_test, 5, 1, 1, 1)
        self.last_sell_price_test = QtWidgets.QLineEdit(self.tab)
        self.last_sell_price_test.setMaximumSize(QtCore.QSize(100, 150))
        self.last_sell_price_test.setObjectName("last_sell_price_test")
        self.gridLayout.addWidget(self.last_sell_price_test, 7, 1, 1, 1)
        self.wallet_BTC_init_test = QtWidgets.QLineEdit(self.tab)
        self.wallet_BTC_init_test.setMaximumSize(QtCore.QSize(100, 150))
        self.wallet_BTC_init_test.setObjectName("wallet_BTC_init_test")
        self.gridLayout.addWidget(self.wallet_BTC_init_test, 8, 1, 1, 1)
        self.existing_real_trades = QtWidgets.QComboBox(self.tab)
        self.existing_real_trades.setEnabled(False)
        self.existing_real_trades.setMaximumSize(QtCore.QSize(100, 150))
        self.existing_real_trades.setEditable(True)
        self.existing_real_trades.setObjectName("existing_real_trades")
        self.gridLayout.addWidget(self.existing_real_trades, 14, 1, 1, 1)
        self.wallet_USD_init_test = QtWidgets.QLineEdit(self.tab)
        self.wallet_USD_init_test.setMaximumSize(QtCore.QSize(100, 150))
        self.wallet_USD_init_test.setObjectName("wallet_USD_init_test")
        self.gridLayout.addWidget(self.wallet_USD_init_test, 9, 1, 1, 1)
        self.test_strategy_button = QtWidgets.QPushButton(self.tab)
        self.test_strategy_button.setEnabled(False)
        self.test_strategy_button.setMaximumSize(QtCore.QSize(250, 250))
        self.test_strategy_button.setObjectName("test_strategy_button")
        self.gridLayout.addWidget(self.test_strategy_button, 10, 0, 1, 2)
        self.timeperiod_test = QtWidgets.QSpinBox(self.tab)
        self.timeperiod_test.setMaximumSize(QtCore.QSize(100, 150))
        self.timeperiod_test.setProperty("value", 9)
        self.timeperiod_test.setObjectName("timeperiod_test")
        self.gridLayout.addWidget(self.timeperiod_test, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMaximumSize(QtCore.QSize(130, 150))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(130, 150))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.investigate_button = QtWidgets.QPushButton(self.tab)
        self.investigate_button.setEnabled(False)
        self.investigate_button.setMaximumSize(QtCore.QSize(100, 150))
        self.investigate_button.setObjectName("investigate_button")
        self.gridLayout.addWidget(self.investigate_button, 17, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMaximumSize(QtCore.QSize(130, 150))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.timeframe_test = QtWidgets.QComboBox(self.tab)
        self.timeframe_test.setMaximumSize(QtCore.QSize(100, 150))
        self.timeframe_test.setObjectName("timeframe_test")
        self.gridLayout.addWidget(self.timeframe_test, 1, 1, 1, 1)
        self.fetch_data_button = QtWidgets.QPushButton(self.tab)
        self.fetch_data_button.setMaximumSize(QtCore.QSize(250, 250))
        self.fetch_data_button.setObjectName("fetch_data_button")
        self.gridLayout.addWidget(self.fetch_data_button, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 16, 0, 1, 1)
        self.get_existing_real_trades_button = QtWidgets.QPushButton(self.tab)
        self.get_existing_real_trades_button.setEnabled(False)
        self.get_existing_real_trades_button.setMaximumSize(QtCore.QSize(250, 250))
        self.get_existing_real_trades_button.setCheckable(False)
        self.get_existing_real_trades_button.setObjectName("get_existing_real_trades_button")
        self.gridLayout.addWidget(self.get_existing_real_trades_button, 13, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMaximumSize(QtCore.QSize(130, 150))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_info = QtWidgets.QLabel(self.tab_2)
        self.label_info.setObjectName("label_info")
        self.horizontalLayout_4.addWidget(self.label_info)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.forse_commit_sell_buy_status_distace_test = QtWidgets.QLineEdit(self.tab_2)
        self.forse_commit_sell_buy_status_distace_test.setMinimumSize(QtCore.QSize(70, 0))
        self.forse_commit_sell_buy_status_distace_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.forse_commit_sell_buy_status_distace_test.setObjectName("forse_commit_sell_buy_status_distace_test")
        self.gridLayout_4.addWidget(self.forse_commit_sell_buy_status_distace_test, 5, 1, 1, 1)
        self.EP_gradient_threshold_test = QtWidgets.QLineEdit(self.tab_2)
        self.EP_gradient_threshold_test.setMinimumSize(QtCore.QSize(70, 0))
        self.EP_gradient_threshold_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.EP_gradient_threshold_test.setObjectName("EP_gradient_threshold_test")
        self.gridLayout_4.addWidget(self.EP_gradient_threshold_test, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 5, 0, 1, 1)
        self.LPP_count_test = QtWidgets.QLineEdit(self.tab_2)
        self.LPP_count_test.setMinimumSize(QtCore.QSize(70, 0))
        self.LPP_count_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.LPP_count_test.setObjectName("LPP_count_test")
        self.gridLayout_4.addWidget(self.LPP_count_test, 0, 1, 1, 1)
        self.buy_threshold_test = QtWidgets.QLineEdit(self.tab_2)
        self.buy_threshold_test.setMinimumSize(QtCore.QSize(70, 0))
        self.buy_threshold_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.buy_threshold_test.setObjectName("buy_threshold_test")
        self.gridLayout_4.addWidget(self.buy_threshold_test, 3, 1, 1, 1)
        self.sell_threshold_test = QtWidgets.QLineEdit(self.tab_2)
        self.sell_threshold_test.setMinimumSize(QtCore.QSize(70, 0))
        self.sell_threshold_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sell_threshold_test.setObjectName("sell_threshold_test")
        self.gridLayout_4.addWidget(self.sell_threshold_test, 4, 1, 1, 1)
        self.independent_last_sell_buy_price_checking_test = QtWidgets.QCheckBox(self.tab_2)
        self.independent_last_sell_buy_price_checking_test.setObjectName("independent_last_sell_buy_price_checking_test")
        self.gridLayout_4.addWidget(self.independent_last_sell_buy_price_checking_test, 6, 0, 1, 2)
        self.LPP_gradients_threshold_test = QtWidgets.QLineEdit(self.tab_2)
        self.LPP_gradients_threshold_test.setMinimumSize(QtCore.QSize(70, 0))
        self.LPP_gradients_threshold_test.setMaximumSize(QtCore.QSize(70, 16777215))
        self.LPP_gradients_threshold_test.setObjectName("LPP_gradients_threshold_test")
        self.gridLayout_4.addWidget(self.LPP_gradients_threshold_test, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.draw_candles = QtWidgets.QCheckBox(self.tab_2)
        self.draw_candles.setEnabled(True)
        self.draw_candles.setChecked(True)
        self.draw_candles.setObjectName("draw_candles")
        self.gridLayout_4.addWidget(self.draw_candles, 7, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.trader_log = QtWidgets.QTextEdit(self.tab_3)
        self.trader_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.trader_log.setObjectName("trader_log")
        self.verticalLayout_3.addWidget(self.trader_log)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 1)
        self.pair_trader = QtWidgets.QComboBox(self.tab_3)
        self.pair_trader.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pair_trader.setObjectName("pair_trader")
        self.gridLayout_9.addWidget(self.pair_trader, 1, 0, 1, 1)
        self.fetch_available_balance_button = QtWidgets.QPushButton(self.tab_3)
        self.fetch_available_balance_button.setObjectName("fetch_available_balance_button")
        self.gridLayout_9.addWidget(self.fetch_available_balance_button, 3, 0, 1, 1)
        self.trader_start_button = QtWidgets.QPushButton(self.tab_3)
        self.trader_start_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.trader_start_button.setObjectName("trader_start_button")
        self.gridLayout_9.addWidget(self.trader_start_button, 3, 2, 1, 1)
        self.trader_status_short_button = QtWidgets.QPushButton(self.tab_3)
        self.trader_status_short_button.setObjectName("trader_status_short_button")
        self.gridLayout_9.addWidget(self.trader_status_short_button, 2, 0, 1, 1)
        self.trader_status_button = QtWidgets.QPushButton(self.tab_3)
        self.trader_status_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.trader_status_button.setObjectName("trader_status_button")
        self.gridLayout_9.addWidget(self.trader_status_button, 1, 1, 1, 1)
        self.trader_stop_button = QtWidgets.QPushButton(self.tab_3)
        self.trader_stop_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.trader_stop_button.setObjectName("trader_stop_button")
        self.gridLayout_9.addWidget(self.trader_stop_button, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.forse_commit_sell_buy_status_distace_trader = QtWidgets.QLineEdit(self.tab_3)
        self.forse_commit_sell_buy_status_distace_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.forse_commit_sell_buy_status_distace_trader.setObjectName("forse_commit_sell_buy_status_distace_trader")
        self.gridLayout_10.addWidget(self.forse_commit_sell_buy_status_distace_trader, 11, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 10, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 9, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 5, 0, 1, 1)
        self.sell_threshold_trader = QtWidgets.QLineEdit(self.tab_3)
        self.sell_threshold_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sell_threshold_trader.setObjectName("sell_threshold_trader")
        self.gridLayout_10.addWidget(self.sell_threshold_trader, 10, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 11, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 8, 0, 1, 1)
        self.LPP_gradients_threshold_trader = QtWidgets.QLineEdit(self.tab_3)
        self.LPP_gradients_threshold_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.LPP_gradients_threshold_trader.setObjectName("LPP_gradients_threshold_trader")
        self.gridLayout_10.addWidget(self.LPP_gradients_threshold_trader, 8, 1, 1, 1)
        self.timeperiod_trader = QtWidgets.QLineEdit(self.tab_3)
        self.timeperiod_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.timeperiod_trader.setObjectName("timeperiod_trader")
        self.gridLayout_10.addWidget(self.timeperiod_trader, 2, 1, 1, 1)
        self.independent_last_sell_buy_price_checking_trader = QtWidgets.QCheckBox(self.tab_3)
        self.independent_last_sell_buy_price_checking_trader.setObjectName("independent_last_sell_buy_price_checking_trader")
        self.gridLayout_10.addWidget(self.independent_last_sell_buy_price_checking_trader, 12, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 4, 0, 1, 1)
        self.LPP_count_trader = QtWidgets.QLineEdit(self.tab_3)
        self.LPP_count_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.LPP_count_trader.setObjectName("LPP_count_trader")
        self.gridLayout_10.addWidget(self.LPP_count_trader, 6, 1, 1, 1)
        self.buy_threshold_trader = QtWidgets.QLineEdit(self.tab_3)
        self.buy_threshold_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.buy_threshold_trader.setObjectName("buy_threshold_trader")
        self.gridLayout_10.addWidget(self.buy_threshold_trader, 9, 1, 1, 1)
        self.last_sell_price_trader = QtWidgets.QLineEdit(self.tab_3)
        self.last_sell_price_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.last_sell_price_trader.setObjectName("last_sell_price_trader")
        self.gridLayout_10.addWidget(self.last_sell_price_trader, 5, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 2, 0, 1, 1)
        self.last_buy_price_trader = QtWidgets.QLineEdit(self.tab_3)
        self.last_buy_price_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.last_buy_price_trader.setObjectName("last_buy_price_trader")
        self.gridLayout_10.addWidget(self.last_buy_price_trader, 4, 1, 1, 1)
        self.EP_gradient_threshold_trader = QtWidgets.QLineEdit(self.tab_3)
        self.EP_gradient_threshold_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.EP_gradient_threshold_trader.setObjectName("EP_gradient_threshold_trader")
        self.gridLayout_10.addWidget(self.EP_gradient_threshold_trader, 7, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 0, 1, 2)
        self.wallet_parts_trader = QtWidgets.QLineEdit(self.tab_3)
        self.wallet_parts_trader.setMaximumSize(QtCore.QSize(70, 16777215))
        self.wallet_parts_trader.setObjectName("wallet_parts_trader")
        self.gridLayout_10.addWidget(self.wallet_parts_trader, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 7, 0, 1, 1)
        self.timeframe_trader = QtWidgets.QComboBox(self.tab_3)
        self.timeframe_trader.setMaximumSize(QtCore.QSize(100, 16777215))
        self.timeframe_trader.setObjectName("timeframe_trader")
        self.gridLayout_10.addWidget(self.timeframe_trader, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.collector_log = QtWidgets.QTextEdit(self.tab_4)
        self.collector_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.collector_log.setObjectName("collector_log")
        self.verticalLayout_4.addWidget(self.collector_log)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.collector_pair_timeframe = QtWidgets.QLineEdit(self.tab_4)
        self.collector_pair_timeframe.setMaximumSize(QtCore.QSize(100, 16777215))
        self.collector_pair_timeframe.setObjectName("collector_pair_timeframe")
        self.gridLayout_11.addWidget(self.collector_pair_timeframe, 4, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 4, 0, 1, 1)
        self.pair_remove_from_collect_button = QtWidgets.QPushButton(self.tab_4)
        self.pair_remove_from_collect_button.setObjectName("pair_remove_from_collect_button")
        self.gridLayout_11.addWidget(self.pair_remove_from_collect_button, 5, 1, 1, 1)
        self.candles_clear_button = QtWidgets.QPushButton(self.tab_4)
        self.candles_clear_button.setObjectName("candles_clear_button")
        self.gridLayout_11.addWidget(self.candles_clear_button, 7, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 6, 0, 1, 1)
        self.candles_clear_all_button = QtWidgets.QPushButton(self.tab_4)
        self.candles_clear_all_button.setObjectName("candles_clear_all_button")
        self.gridLayout_11.addWidget(self.candles_clear_all_button, 7, 1, 1, 1)
        self.pair_add_to_collect_button = QtWidgets.QPushButton(self.tab_4)
        self.pair_add_to_collect_button.setObjectName("pair_add_to_collect_button")
        self.gridLayout_11.addWidget(self.pair_add_to_collect_button, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.candles_info_button = QtWidgets.QPushButton(self.tab_4)
        self.candles_info_button.setObjectName("candles_info_button")
        self.gridLayout_11.addWidget(self.candles_info_button, 7, 2, 1, 1)
        self.trades_history_tree = QtWidgets.QTreeWidget(self.tab_4)
        self.trades_history_tree.setMinimumSize(QtCore.QSize(600, 0))
        self.trades_history_tree.setAlternatingRowColors(True)
        self.trades_history_tree.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.trades_history_tree.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.trades_history_tree.setColumnCount(0)
        self.trades_history_tree.setObjectName("trades_history_tree")
        self.gridLayout_11.addWidget(self.trades_history_tree, 3, 0, 1, 3)
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 2, 0, 1, 1)
        self.collector_stop_button = QtWidgets.QPushButton(self.tab_4)
        self.collector_stop_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.collector_stop_button.setObjectName("collector_stop_button")
        self.gridLayout_11.addWidget(self.collector_stop_button, 1, 2, 1, 1)
        self.collector_start_button = QtWidgets.QPushButton(self.tab_4)
        self.collector_start_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.collector_start_button.setObjectName("collector_start_button")
        self.gridLayout_11.addWidget(self.collector_start_button, 2, 2, 1, 1)
        self.collector_status_button = QtWidgets.QPushButton(self.tab_4)
        self.collector_status_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.collector_status_button.setObjectName("collector_status_button")
        self.gridLayout_11.addWidget(self.collector_status_button, 1, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_11)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crypto Trader"))
        self.label_3.setText(_translate("MainWindow", "End:"))
        self.label_2.setText(_translate("MainWindow", "Begin:"))
        self.range_begin_dt.setDisplayFormat(_translate("MainWindow", "dd/M/yy HH:mm"))
        self.range_end_dt.setDisplayFormat(_translate("MainWindow", "dd/M/yy HH:mm"))
        self.clear_main_plot_button.setText(_translate("MainWindow", "Clear"))
        self.show_real_button.setText(_translate("MainWindow", "Show real"))
        self.label_6.setText(_translate("MainWindow", "Wallet parts:"))
        self.label.setText(_translate("MainWindow", "Pair:"))
        self.label_4.setText(_translate("MainWindow", "Timeframe:"))
        self.label_11.setText(_translate("MainWindow", "Trades (start date):"))
        self.label_5.setText(_translate("MainWindow", "Timeperiod:"))
        self.ts_analysis_button.setText(_translate("MainWindow", "Statistical analysis"))
        self.wallet_BTC_init_test.setText(_translate("MainWindow", "0.0"))
        self.wallet_USD_init_test.setText(_translate("MainWindow", "200.0"))
        self.test_strategy_button.setText(_translate("MainWindow", "Test strategy"))
        self.label_8.setText(_translate("MainWindow", "Last SELL price:"))
        self.label_9.setText(_translate("MainWindow", "BTC wallet balance:"))
        self.investigate_button.setText(_translate("MainWindow", "Auto test"))
        self.label_10.setText(_translate("MainWindow", "USD wallet balance:"))
        self.fetch_data_button.setText(_translate("MainWindow", "Update init data"))
        self.get_existing_real_trades_button.setText(_translate("MainWindow", "Fetch real trades data"))
        self.label_7.setText(_translate("MainWindow", "Last BUY price:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Strategy test"))
        self.label_info.setText(_translate("MainWindow", "INFO PIC"))
        self.forse_commit_sell_buy_status_distace_test.setText(_translate("MainWindow", "#60*24*2"))
        self.EP_gradient_threshold_test.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Force Order Interval (FOI). \n"
"Force commit \'sell<->buy\' order distace (minutes): \n"
"(# - Ignore)"))
        self.LPP_count_test.setText(_translate("MainWindow", "1"))
        self.buy_threshold_test.setText(_translate("MainWindow", "1.5"))
        self.sell_threshold_test.setText(_translate("MainWindow", "1.5"))
        self.independent_last_sell_buy_price_checking_test.setText(_translate("MainWindow", "Independent last sell/buy price checking"))
        self.LPP_gradients_threshold_test.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "(MSP) Min BUY profit per order besides fee (%):"))
        self.label_13.setText(_translate("MainWindow", "EP gradient threshold:"))
        self.label_12.setText(_translate("MainWindow", "Count of LPP:"))
        self.label_14.setText(_translate("MainWindow", "LPP gradients threshold:"))
        self.draw_candles.setText(_translate("MainWindow", "Draw candles"))
        self.label_16.setText(_translate("MainWindow", "(MBP) Min SELL profit per order besides fee (%):"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Strategy test - settings"))
        self.label_20.setText(_translate("MainWindow", "Trader:"))
        self.fetch_available_balance_button.setText(_translate("MainWindow", "Get Balance"))
        self.trader_start_button.setText(_translate("MainWindow", "Start"))
        self.trader_status_short_button.setText(_translate("MainWindow", "Short log"))
        self.trader_status_button.setText(_translate("MainWindow", "Full log"))
        self.trader_stop_button.setText(_translate("MainWindow", "Stop"))
        self.forse_commit_sell_buy_status_distace_trader.setText(_translate("MainWindow", "#60*24*2"))
        self.label_30.setText(_translate("MainWindow", "(MSP) Min SELL profit per order besides fee (%):"))
        self.label_28.setText(_translate("MainWindow", "(MSP) Min BUY profit per order besides fee (%):"))
        self.label_25.setText(_translate("MainWindow", "Last SELL price:"))
        self.sell_threshold_trader.setText(_translate("MainWindow", "1.5"))
        self.label_31.setText(_translate("MainWindow", "Force Order Interval (FOI). \n"
"Force commit \'sell<->buy\' order distace (minutes): \n"
"(# - Ignore)"))
        self.label_29.setText(_translate("MainWindow", "LPP gradients threshold:"))
        self.LPP_gradients_threshold_trader.setText(_translate("MainWindow", "0"))
        self.timeperiod_trader.setText(_translate("MainWindow", "9"))
        self.independent_last_sell_buy_price_checking_trader.setText(_translate("MainWindow", "Independent last sell/buy price checking"))
        self.label_24.setText(_translate("MainWindow", "Last BUY price:"))
        self.LPP_count_trader.setText(_translate("MainWindow", "1"))
        self.buy_threshold_trader.setText(_translate("MainWindow", "1.5"))
        self.last_sell_price_trader.setText(_translate("MainWindow", "inherit"))
        self.label_26.setText(_translate("MainWindow", "Count of LPP:"))
        self.label_22.setText(_translate("MainWindow", "Timeperiod:"))
        self.last_buy_price_trader.setText(_translate("MainWindow", "inherit"))
        self.EP_gradient_threshold_trader.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "Wallet parts:"))
        self.label_21.setText(_translate("MainWindow", "Trader settings (for start):"))
        self.wallet_parts_trader.setText(_translate("MainWindow", "2"))
        self.label_27.setText(_translate("MainWindow", "EP gradient threshold:"))
        self.label_18.setText(_translate("MainWindow", "Timeframe:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Backend - Trader"))
        self.collector_pair_timeframe.setPlaceholderText(_translate("MainWindow", "XMRUSD::1m"))
        self.label_32.setText(_translate("MainWindow", "Pair:"))
        self.pair_remove_from_collect_button.setText(_translate("MainWindow", "Remove from collect"))
        self.candles_clear_button.setText(_translate("MainWindow", "Clear"))
        self.label_33.setText(_translate("MainWindow", "Candles:"))
        self.candles_clear_all_button.setText(_translate("MainWindow", "Clear ALL"))
        self.pair_add_to_collect_button.setText(_translate("MainWindow", "Add to collect"))
        self.label_19.setText(_translate("MainWindow", "Collector:"))
        self.candles_info_button.setText(_translate("MainWindow", "Info"))
        self.label_34.setText(_translate("MainWindow", "Trades history:"))
        self.collector_stop_button.setText(_translate("MainWindow", "Stop"))
        self.collector_start_button.setText(_translate("MainWindow", "Start"))
        self.collector_status_button.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Backend - Collector"))

from pyqtgraph import GraphicsWindow
